"""add summary tables and pr body head_sha

Revision ID: 3b12d9bb28ff
Revises: e70a977c6d59
Create Date: 2026-07-09 01:26:15.494466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b12d9bb28ff'
down_revision: Union[str, None] = 'e70a977c6d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contribution_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('github_login', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_hash', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'github_login')
    )
    op.create_table('pr_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('author_login', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_hash', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'pr_number')
    )
    op.create_index('ix_pr_summaries_project_author', 'pr_summaries', ['project_id', 'author_login'], unique=False)
    op.create_table('summary_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('github_login', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_prs', sa.Integer(), nullable=False),
    sa.Column('done_prs', sa.Integer(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_summary_jobs_project_login', 'summary_jobs', ['project_id', 'github_login'], unique=False)
    op.add_column('github_pull_requests', sa.Column('body', sa.Text(), nullable=True))
    op.add_column('github_pull_requests', sa.Column('head_sha', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_pull_requests', 'head_sha')
    op.drop_column('github_pull_requests', 'body')
    op.drop_index('ix_summary_jobs_project_login', table_name='summary_jobs')
    op.drop_table('summary_jobs')
    op.drop_index('ix_pr_summaries_project_author', table_name='pr_summaries')
    op.drop_table('pr_summaries')
    op.drop_table('contribution_summaries')
    # ### end Alembic commands ###
